# Generated by Django 5.1.3 on 2025-01-03 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Latitude',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='Longitude',
            new_name='longitude',
        ),
    ]
