services:
  db:
    image: postgres:15.9-alpine3.20
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: django_app
    volumes:
      - ./static_volume:/src/static
    command: >
      sh -c "chmod -R 755 /src/static &&
             poetry run python manage.py migrate &&
             poetry run gunicorn weather_viewer.wsgi:application --bind 0.0.0.0:8000"
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    build:
      context: ./docker/nginx/
    container_name: nginx
    volumes:
      - static_volume:/src/static
    depends_on:
      - web
    ports:
      - "8000:80"


volumes:
  postgres_data:
  static_volume: