FROM python:3.12-alpine

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN apk update && \
    apk add --no-cache gcc musl-dev postgresql-dev

# Устанавливаем Poetry
RUN pip install --no-cache-dir poetry


# Добавляем Poetry в PATH
ENV PATH="/root/.local/bin:${PATH}"

WORKDIR /src

# Копируем файлы Poetry
COPY pyproject.toml poetry.lock ./

# Устанавливаем зависимости
RUN poetry install --no-root --no-interaction --no-ansi

COPY /src .

CMD ["poetry", "run", "python", "manage.py", "runserver", "0.0.0.0:8000"]