services:
  db:
    image: postgres:15.9-alpine3.20
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django_app
    volumes:
      - ./src:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped


volumes:
  postgres_data: